"""Tables for queued reports and ratings. No user identity, no IP address, coarse location."""

import uuid
from datetime import UTC, datetime

from sqlalchemy import Boolean, DateTime, Float, Integer, String, Text, Uuid
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


def _now() -> datetime:
    return datetime.now(UTC)


class _Row:
    # The id is generated by the client while offline, which is also what makes sync idempotent.
    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    site_id: Mapped[str] = mapped_column(String(64), index=True)
    received_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)


class RoadReportRow(_Row, Base):
    __tablename__ = "road_reports"
    reported_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    route_id: Mapped[str] = mapped_column(String(64))
    condition: Mapped[str] = mapped_column(String(16))
    lat: Mapped[float | None] = mapped_column(Float, nullable=True)
    lon: Mapped[float | None] = mapped_column(Float, nullable=True)
    note: Mapped[str] = mapped_column(String(500), default="")


class SiteStatusReportRow(_Row, Base):
    __tablename__ = "site_status_reports"
    reported_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    status: Mapped[str] = mapped_column(String(16))
    lat: Mapped[float | None] = mapped_column(Float, nullable=True)
    lon: Mapped[float | None] = mapped_column(Float, nullable=True)
    note: Mapped[str] = mapped_column(String(500), default="")


class AdviceRatingRow(_Row, Base):
    __tablename__ = "advice_ratings"
    rated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    helpful: Mapped[bool] = mapped_column(Boolean)
    comment: Mapped[str] = mapped_column(String(500), default="")


class PublishedDeltaRow(Base):
    """The newest weather and news delta per site, so a scheduled job can refresh it without a
    redeploy. The API serves this when it is newer than the delta bundled with the deploy."""

    __tablename__ = "published_deltas"
    site_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    payload: Mapped[str] = mapped_column(Text)  # the Delta as JSON
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)


class RateLimitRow(Base):
    """Request counts per hour for report endpoints. The key is a salted hash of the client
    address that changes daily, never the address itself, and rows are purged after two days."""

    __tablename__ = "rate_limits"
    key: Mapped[str] = mapped_column(String(64), primary_key=True)
    window_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), primary_key=True)
    count: Mapped[int] = mapped_column(Integer)


class ItineraryCacheRow(Base):
    """Model-written itineraries, keyed by everything that shaped them. Holds no personal data
    beyond the trip request itself (dates, group size), and is what makes repeats free."""

    __tablename__ = "itinerary_cache"
    key: Mapped[str] = mapped_column(String(64), primary_key=True)
    site_id: Mapped[str] = mapped_column(String(64), index=True)
    payload: Mapped[str] = mapped_column(Text)  # Itinerary JSON
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now, index=True)
