"""Tables for queued reports and ratings. No user identity, no IP address, coarse location."""

import uuid
from datetime import UTC, datetime

from sqlalchemy import Boolean, DateTime, Float, String, Uuid
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


def _now() -> datetime:
    return datetime.now(UTC)


class _Row:
    # The id is generated by the client while offline, which is also what makes sync idempotent.
    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)
    site_id: Mapped[str] = mapped_column(String(64), index=True)
    received_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)


class RoadReportRow(_Row, Base):
    __tablename__ = "road_reports"
    reported_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    route_id: Mapped[str] = mapped_column(String(64))
    condition: Mapped[str] = mapped_column(String(16))
    lat: Mapped[float | None] = mapped_column(Float, nullable=True)
    lon: Mapped[float | None] = mapped_column(Float, nullable=True)
    note: Mapped[str] = mapped_column(String(500), default="")


class SiteStatusReportRow(_Row, Base):
    __tablename__ = "site_status_reports"
    reported_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    status: Mapped[str] = mapped_column(String(16))
    lat: Mapped[float | None] = mapped_column(Float, nullable=True)
    lon: Mapped[float | None] = mapped_column(Float, nullable=True)
    note: Mapped[str] = mapped_column(String(500), default="")


class AdviceRatingRow(_Row, Base):
    __tablename__ = "advice_ratings"
    rated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    helpful: Mapped[bool] = mapped_column(Boolean)
    comment: Mapped[str] = mapped_column(String(500), default="")
